<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="fr" >  
<head>
<title> SPARKBox </title>
<meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1" />
<meta name="Description" content="SPARKBox, Gestion de chauffage Thermique">
<meta name="keywords" content="SPARKBox">
<link href="/sparkbox.css" rel="stylesheet" type="text/css" />
<link rel="icon" type="image/png" href="/icone_16.png" />
<script src="/sparkbox.js" type="text/javascript"></script>
</head>
<body>
<div id="shadow-one">
    <div id="shadow-two">
        <div id="shadow-three">
            <div id="shadow-four">
                <div id="page">
                    <div style="padding:0 0 30px 0px"><img src="/sparkbox.jpg" alt="Logo SPARKBox"/></div>
                    